### ISSUE TITLE
Hi I keep getting ( Channel Not Found ) message ,using windows & Roku 3, was working fine. anybody else having a problem

### ISSUE THREAD

**Issue by aj031679** [sander1/Disney-Junior.bundle#1]

**Comment by sander1** [comment]
Fixed with https://github.com/sander1/Disney-Junior.bundle/commit/3a16d4a17fc3f637a3e46ac1a48327b49c3bd146 and https://github.com/plexinc-plugins/Services.bundle/commit/b9e1e5d025bff96fa130fe9bf8563fd2836fac15

Services bundle update will be released shortly.

**Comment by aj031679** [comment]
Thank You For Your Help!!

Date: Wed, 22 Jul 2015 06:11:19 -0700
